// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyPulse.Infrastructure.Services;

#nullable disable

namespace SkyPulse.Web.Migrations
{
    [DbContext(typeof(SkyPulseDbContext))]
    partial class SkyPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyPulse.Core.Models.TelemetrySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EnterpriseRiskScore")
                        .HasColumnType("float");

                    b.Property<double>("ProtonDensity")
                        .HasColumnType("float");

                    b.Property<double>("ProtonSpeed")
                        .HasColumnType("float");

                    b.Property<double>("ProtonTemperature")
                        .HasColumnType("float");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SatelliteSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TimeTag")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TelemetrySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
